### ISSUE TITLE
Move docs/source/conf.py to docs/conf.py?

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage_sample#14]
Looking at other projects, this feels more standard, and it reduces the depth by one. But I might be biased.

**Comment by jdemeyer** [comment]
> Looking at other projects, this feels more standard, and it reduces the depth by one. But I might be biased.

I believe that `docs/source/conf.py` is actually the Sphinx default.

**Comment by zerline** [comment]
Closing this old issue as we did not reach a consensus. cc @nthiery @jdemeyer
