### ISSUE TITLE
docs: _static subdirectory not present

### ISSUE THREAD

**Issue by zerline** [sagemath/sage_sample#29]
When you "make html" within the ./docs subdirectory, you get a warning:

--%<
copying static files... WARNING: html_static_path entry u'/home/odile/odk/sage/git/sage_sample/docs/source/_static' does not exist
--%<

This warning would disappear if you change line #167 in file ./docs/source/conf.py

#html_static_path = ['_static']
html_static_path = []

As CSS file is not actually required ..

**Comment by nthiery** [comment]
Good point. Fixed in 08cd20f44c463d22042c6c36fbd7dd3d402274ec. Thanks!
