### ISSUE TITLE
binder support

### ISSUE THREAD

**Issue by nthiery** [sagemath/sage_sample#3]
[binder](http://mybinder.org) is a neat web service that gives interactive access to the Jupyter notebooks stored in a GitHub repository. It would be neat to showcase how to include demo notebooks in the package that users can immediately play with on mybinder.

Prerequisite: https://github.com/sagemath/docker-images/issues/23

**Comment by koffie** [comment]
This sounds nice, note that [github also has builtin jupyter support](https://github.com/blog/1995-github-jupyter-notebooks-3), although admittedly this is non-interactive. So a good start would be to just include a non-interactive notebook first, and then later add support for interactivity. P.s. do you happen to know wether one can "doctest" a jupyter notebook?

**Comment by nthiery** [comment]
>    This sounds nice, note that [1]github also has builtin jupyter support,
>    although admittedly this is non-interactive. So a good start would be
>    to just include a non-interactive notebook first, and then later add
>    support for interactivity.

Indeed.

>    P.s. do you happen to know wether one can "doctest" a jupyter
>    notebook?

Yes; see: https://github.com/computationalmodelling/nbval

**Comment by nthiery** [comment]
Implemented in a6f2d055d1433417662c284be09cadc5d6227d09 and follow-ups.

**Comment by nthiery** [comment]
See binder link on top of the README at https://github.com/sagemath/sage_sample ,
