### ISSUE TITLE
Incorrect uninstall in makefile ?

### ISSUE THREAD

**Issue by egourgoulhon** [sagemath/sage_sample#31]
In the [makefile](https://github.com/sagemath/sage_sample/blob/master/makefile), shouldn't the target  `uninstall` be
`$(SAGE) -pip uninstall PACKAGE`
instead of
`$(SAGE) -pip uninstall .`
?

**Comment by nthiery** [comment]
Hi Eric!

Both should work, should't they? Since we use `sage -pip install .` using the same for uninstall seems consistent; or do you see an advantage to using `$PACKAGE`?

**Comment by egourgoulhon** [comment]
Well, with `$(SAGE) -pip uninstall .` one gets the error 
`You must give at least one requirement to uninstall (see "pip help uninstall")`
since `pip uninstall` is expecting a *package* name, not a directory. 
In this respect, `pip install` and `pip uninstall` are not symmetric.

**Comment by koffie** [comment]
Hi Eric,

It might also depend on the version of pip you are using. I have run into other problems with sage_sample in the past that were working in some point, but then pip changed. Anyway the python zen says "Explicit is better than implicit" so I feel more comfortable using the explicit `$PACKAGE` as you suggest then the implicit `.`

**Comment by nthiery** [comment]
Hmm, it indeed did not work. Either I confused myself, or it used to
work and not anymore. Anyway, a pull request to fix that is welcome!
Thanks for pointing this out.

**Comment by egourgoulhon** [comment]
Pull request submitted, but Travis CI reports a 404 error a priori not connected with the proposed change in the makefile.

**Comment by nthiery** [comment]
Fixed by https://github.com/sagemath/sage_sample/pull/32; indeed the Travis error is unrelated.

**Comment by nthiery** [comment]
Thanks Eric!

**Comment by egourgoulhon** [comment]
You're welcome. Thanks to you and to the other authors for this sample package. It's very helpful! (I am using it to construct a new Sage package).
