### ISSUE TITLE
Example of packaging an executable

### ISSUE THREAD

**Issue by nvcleemp** [sagemath/sage_sample#38]
This sample seems to focus on packaging pure Python code. I mainly used Sage packaging to package some programs written in different languages, that were then compiled and copied to `$SAGE_LOCAL/bin`. I don't see how this can be achieved with the technique explained in this sample.

**Comment by nthiery** [comment]
> This sample seems to focus on packaging pure Python code. I mainly
> used Sage packaging to package some programs written in different
> languages, that were then compiled and copied to `$SAGE_LOCAL/bin`.
> I don't see how this can be achieved with the technique explained in
> this sample.

This repository is meant as an example of how to write a Python
package (possibly with Cython extensions) that uses Sage. Packaging
software for use by Sage is an important but different problem.

Cheers,
